### ISSUE TITLE
Feat Req: Get reactions by author

### ISSUE THREAD

**Issue by fontanon** [VirtusLab-Open-Source/strapi-plugin-reactions#13]
Hi. I'd like to request to include something like `GET <host>/api/reactions/author/<id>/<?kind>`. Similar to the one offered on strapi-plugin-comments: https://github.com/VirtusLab-Open-Source/strapi-plugin-comments#get-comments-by-author

That way, apps using reactions plugin would offer registered users the ability to list all their reactions on the same site, and to manage them (edit or remove).

**Comment by fontanon** [comment]
Hi @cyp3rius I'd like to know if there is any plans for this. Thanks.

**Comment by cyp3rius** [comment]
Working on that for `3.x` now

**Comment by fontanon** [comment]
> Working on that for `3.x` now

Great @cyp3rius. Is it `3.x` planned to be available for Strapi v4 or only Strapi v5?

**Comment by cyp3rius** [comment]
the `2.x` (I meant that :) ) is Strapi 5 based. For Strapi 4 and versions `1.x` we're not providing any features requests.

**Comment by cyp3rius** [comment]
Released in `v2.1.0`
