### ISSUE TITLE
Does stapi 4.19.0 supported?

### ISSUE THREAD

**Issue by 111Tashmo** [VirtusLab-Open-Source/strapi-plugin-reactions#18]

**Comment by 111Tashmo** [comment]
after configurating the reaction and restart strapi, the strapi panel cant show the detail page of entries, (when I clik on any entry, It's a empty page), but terminal shows I have assese in.

**Comment by cyp3rius** [comment]
We recommend to check version `1.1.4` which should be compatible with 4.19/4.20

Later versions are aligned to recent Strapi versions and because of the dependencies might not work properly with older ones.
